import gzip
import json
import shutil
import subprocess
from pathlib import Path

import pytest

VALIDATION_DIR = Path(__file__).parent
GROUND_TRUTH_PATH = VALIDATION_DIR / "ground_truth.json"
DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_r_ground_truth.R"


def _r_sceptre_available() -> bool:
    try:
        result = subprocess.run(
            ["Rscript", "-e", "library(sceptre)"],
            capture_output=True,
            timeout=30,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


@pytest.fixture(scope="session")
def ground_truth():
    if not GROUND_TRUTH_PATH.exists():
        if not _r_sceptre_available():
            pytest.skip("R/sceptre not available and no cached ground_truth.json present")
        subprocess.run(["Rscript", str(DUMP_SCRIPT), str(GROUND_TRUTH_PATH), "4"], check=True)
    with open(GROUND_TRUTH_PATH) as f:
        return json.load(f)


PERTURBPLAN_GROUND_TRUTH_PATH = VALIDATION_DIR / "perturbplan_ground_truth.json"
PERTURBPLAN_DUMP_SCRIPT = (
    VALIDATION_DIR.parent.parent / "scripts" / "dump_perturbplan_ground_truth.R"
)


def _r_perturbplan_available() -> bool:
    try:
        result = subprocess.run(
            ["Rscript", "-e", "library(perturbplan)"],
            capture_output=True,
            timeout=60,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


@pytest.fixture(scope="session")
def perturbplan_ground_truth():
    """PerturbPlan's own output for the analytical power port.

    Regenerated only if the JSON is missing, like `ground_truth`, so CI needs
    neither R nor perturbplan. If you change
    `scripts/dump_perturbplan_ground_truth.R`, delete the JSON or the tests
    keep validating against the stale fixture.
    """
    if not PERTURBPLAN_GROUND_TRUTH_PATH.exists():
        if not _r_perturbplan_available():
            pytest.skip(
                "R/perturbplan not available and no cached perturbplan_ground_truth.json present"
            )
        subprocess.run(
            ["Rscript", str(PERTURBPLAN_DUMP_SCRIPT), str(PERTURBPLAN_GROUND_TRUTH_PATH)],
            check=True,
        )
    with open(PERTURBPLAN_GROUND_TRUTH_PATH) as f:
        return json.load(f)


POSCOUNTS_GROUND_TRUTH_PATH = VALIDATION_DIR / "poscounts_ground_truth.json"
POSCOUNTS_DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_poscounts_ground_truth.R"


def _r_deseq2_available() -> bool:
    try:
        result = subprocess.run(
            ["Rscript", "-e", "library(DESeq2)"],
            capture_output=True,
            timeout=120,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


@pytest.fixture(scope="session")
def poscounts_ground_truth():
    """DESeq2's own poscounts size factors, for the baseline-mean helper.

    DESeq2 defines the estimator, so it is the reference rather than a second
    transcription of the same arithmetic. Regenerated only if the JSON is
    missing, so CI needs neither R nor DESeq2; delete the JSON if you change
    `scripts/dump_poscounts_ground_truth.R`.
    """
    if not POSCOUNTS_GROUND_TRUTH_PATH.exists():
        if not _r_deseq2_available():
            pytest.skip("R/DESeq2 not available and no cached poscounts_ground_truth.json present")
        subprocess.run(
            ["Rscript", str(POSCOUNTS_DUMP_SCRIPT), str(POSCOUNTS_GROUND_TRUTH_PATH)], check=True
        )
    with open(POSCOUNTS_GROUND_TRUTH_PATH) as f:
        return json.load(f)


SINGLETON_GROUND_TRUTH_PATH = VALIDATION_DIR / "singleton_ground_truth.json"
SINGLETON_DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_singleton_ground_truth.R"


@pytest.fixture(scope="session")
def singleton_ground_truth():
    """sceptre's own pair expansion under `grna_integration_strategy="singleton"`.

    Generated by calling `update_dfs_based_on_grouping_strategy` on minimal
    sceptre objects, so it is their function rather than a reading of it.
    Regenerated only if the JSON is missing; delete it if you change
    `scripts/dump_singleton_ground_truth.R`.
    """
    if not SINGLETON_GROUND_TRUTH_PATH.exists():
        if not _r_sceptre_available():
            pytest.skip("R/sceptre not available and no cached singleton_ground_truth.json")
        subprocess.run(
            ["Rscript", str(SINGLETON_DUMP_SCRIPT), str(SINGLETON_GROUND_TRUTH_PATH)], check=True
        )
    with open(SINGLETON_GROUND_TRUTH_PATH) as f:
        return json.load(f)


LOWMOI_GROUND_TRUTH_PATH = VALIDATION_DIR / "lowmoi_ground_truth.json.gz"
LOWMOI_DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_lowmoi_ground_truth.R"


@pytest.fixture(scope="session")
def lowmoi_ground_truth():
    """sceptre's own low-MOI numbers, from its simulated example data.

    Committed gzipped, to stay under the repository's large-file limit.
    Regenerated only if missing, like `ground_truth`; delete it if you change
    `scripts/dump_lowmoi_ground_truth.R`. It records the sceptre version and
    install SHA that produced it.
    """
    if not LOWMOI_GROUND_TRUTH_PATH.exists():
        if not _r_sceptre_available():
            pytest.skip("R/sceptre not available and no cached lowmoi_ground_truth.json.gz")
        plain = LOWMOI_GROUND_TRUTH_PATH.with_suffix("")
        subprocess.run(["Rscript", str(LOWMOI_DUMP_SCRIPT), str(plain)], check=True)
        # mtime=0, so regenerating the same JSON gives the same bytes.
        with open(plain, "rb") as fin, open(LOWMOI_GROUND_TRUTH_PATH, "wb") as raw:
            with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as fout:
                shutil.copyfileobj(fin, fout)
        plain.unlink()
    with gzip.open(LOWMOI_GROUND_TRUTH_PATH, "rt") as f:
        return json.load(f)


def _r_has(package: str, timeout: int = 60) -> bool:
    try:
        result = subprocess.run(
            ["Rscript", "-e", f"library({package})"],
            capture_output=True,
            timeout=timeout,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _dump_gzipped(dump_script: Path, gz_path: Path) -> None:
    plain = gz_path.with_suffix("")
    subprocess.run(["Rscript", str(dump_script), str(plain)], check=True)
    # mtime=0, so regenerating the same JSON gives the same bytes.
    with open(plain, "rb") as fin, open(gz_path, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as fout:
            shutil.copyfileobj(fin, fout)
    plain.unlink()


FISHASH_GROUND_TRUTH_PATH = VALIDATION_DIR / "fishash_ground_truth.json.gz"
FISHASH_DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_fishash_ground_truth.R"


@pytest.fixture(scope="session")
def fishash_ground_truth():
    """fishash's own numbers for the port in `pysceptre.assignment`, on synthetic data.

    Committed gzipped and regenerated only if missing, like `lowmoi_ground_truth`; delete it if
    you change `scripts/dump_fishash_ground_truth.R` (a test compares the md5 it records).
    """
    if not FISHASH_GROUND_TRUTH_PATH.exists():
        if not _r_has("fishash"):
            pytest.skip("R/fishash not available and no cached fishash_ground_truth.json.gz")
        _dump_gzipped(FISHASH_DUMP_SCRIPT, FISHASH_GROUND_TRUTH_PATH)
    with gzip.open(FISHASH_GROUND_TRUTH_PATH, "rt") as f:
        return json.load(f)


ASSIGNMENT_RULES_GROUND_TRUTH_PATH = VALIDATION_DIR / "assignment_rules_ground_truth.json.gz"
ASSIGNMENT_RULES_DUMP_SCRIPT = (
    VALIDATION_DIR.parent.parent / "scripts" / "dump_assignment_rules_ground_truth.R"
)


@pytest.fixture(scope="session")
def assignment_rules_ground_truth():
    """sceptre 0.10.3's thresholding and maximum assignment on synthetic gRNA counts.

    Committed gzipped and regenerated only if missing; delete it if you change
    `scripts/dump_assignment_rules_ground_truth.R` (a test compares the md5 it records).
    """
    if not ASSIGNMENT_RULES_GROUND_TRUTH_PATH.exists():
        if not _r_sceptre_available():
            pytest.skip(
                "R/sceptre not available and no cached assignment_rules_ground_truth.json.gz"
            )
        _dump_gzipped(ASSIGNMENT_RULES_DUMP_SCRIPT, ASSIGNMENT_RULES_GROUND_TRUTH_PATH)
    with gzip.open(ASSIGNMENT_RULES_GROUND_TRUTH_PATH, "rt") as f:
        return json.load(f)


@pytest.fixture(params=["numba", "numpy"])
def assignment_kernel(request, monkeypatch):
    """Run a test once on the numba kernels and once on the numpy fallback.

    On the numpy pass the jitted entry points are replaced by functions that raise, so a test
    that passes there really ran the fallback.
    """
    from pysceptre.assignment import hypergeom, mixture

    if request.param == "numba":
        if not (hypergeom._HAVE_NUMBA and mixture._HAVE_NUMBA):
            pytest.skip("numba is not installed")
        return request.param

    def _forbidden(*args, **kwargs):
        raise AssertionError("a numba kernel ran on the numpy path")

    monkeypatch.setattr(hypergeom, "_HAVE_NUMBA", False)
    monkeypatch.setattr(hypergeom, "_log_phyper_loop", _forbidden)
    monkeypatch.setattr(mixture, "_HAVE_NUMBA", False)
    monkeypatch.setattr(mixture, "_reduced_em_jit", _forbidden)
    return request.param


MIXTURE_GROUND_TRUTH_PATH = VALIDATION_DIR / "mixture_ground_truth.json.gz"
MIXTURE_DUMP_SCRIPT = VALIDATION_DIR.parent.parent / "scripts" / "dump_mixture_ground_truth.R"


@pytest.fixture(scope="session")
def mixture_ground_truth():
    """sceptre 0.10.3's mixture assignment on synthetic gRNA rows, internals included.

    Committed gzipped and regenerated only if missing; delete it if you change
    `scripts/dump_mixture_ground_truth.R` (a test compares the md5 it records).
    """
    if not MIXTURE_GROUND_TRUTH_PATH.exists():
        if not _r_sceptre_available():
            pytest.skip("R/sceptre not available and no cached mixture_ground_truth.json.gz")
        _dump_gzipped(MIXTURE_DUMP_SCRIPT, MIXTURE_GROUND_TRUTH_PATH)
    with gzip.open(MIXTURE_GROUND_TRUTH_PATH, "rt") as f:
        return json.load(f)
