"""The analytical power port against PerturbPlan's own R output.

The fixture is generated by `scripts/dump_perturbplan_ground_truth.R` from the
installed `perturbplan` and cached in
`tests/validation/perturbplan_ground_truth.json`, so these run with no R.

Tolerance is relative rather than exact. `cutoff = alpha / 2` puts the normal
tail at p ~ 3e-5, where R's `pnorm`/`qnorm` and scipy's `norm.cdf`/`norm.ppf`
need not agree to the last bit.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from pysceptre.analytical_power import (
    compute_power,
    target_cell_counts,
    var_nb,
    zero_prob,
)

# Relative agreement required against R, on values spanning ~1e-58 to 1.
RTOL = 1e-9
ATOL = 1e-12


def _frames(gt: dict) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    return (
        pd.DataFrame(gt["discovery_pairs"]),
        pd.DataFrame(gt["cells_per_grna"]),
        pd.DataFrame(gt["baseline_expression_stats"]),
    )


def test_fixture_records_its_provenance(perturbplan_ground_truth):
    """A fixture that does not name the version that produced it cannot be audited."""
    gt = perturbplan_ground_truth
    assert gt["perturbplan_version"]
    assert len(gt["perturbplan_sha"]) == 40, gt["perturbplan_sha"]
    assert gt["control_group"] == "complement"
    assert len(gt["cases"]) > 0


def test_power_matches_r_for_every_case(perturbplan_ground_truth):
    """The whole point: same inputs, same numbers as `compute_power()`."""
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)

    for case in gt["cases"]:
        got = compute_power(
            pairs,
            cells_per_grna,
            baseline,
            fold_change_mean=case["fold_change_mean"],
            fold_change_sd=case["fold_change_sd"],
            cutoff=case["cutoff"],
            num_total_cells=gt["num_total_cells"],
            side=case["side"],
            n_nonzero_trt_thresh=case["n_nonzero_trt_thresh"],
            n_nonzero_cntrl_thresh=case["n_nonzero_cntrl_thresh"],
        )
        # R returns the pairs in the order supplied, and so does the port, but comparing on the
        # keys rather than on position means a future reordering fails loudly instead of quietly
        # comparing the wrong rows.
        expected = pd.DataFrame(
            {
                "grna_target": case["grna_target"],
                "response_id": case["response_id"],
                "r_power": case["power"],
            }
        )
        merged = got.merge(expected, on=["grna_target", "response_id"], how="outer")
        assert len(merged) == len(expected), case["label"]
        assert merged["power"].notna().all(), case["label"]
        np.testing.assert_allclose(
            merged["power"].to_numpy(),
            merged["r_power"].to_numpy(),
            rtol=RTOL,
            atol=ATOL,
            err_msg=f"case {case['label']}",
        )


def test_expected_num_discoveries_matches_r(perturbplan_ground_truth):
    """R also returns the summed power; it is a cheap independent check of the whole vector."""
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    for case in gt["cases"]:
        got = compute_power(
            pairs,
            cells_per_grna,
            baseline,
            fold_change_mean=case["fold_change_mean"],
            fold_change_sd=case["fold_change_sd"],
            cutoff=case["cutoff"],
            num_total_cells=gt["num_total_cells"],
            side=case["side"],
            n_nonzero_trt_thresh=case["n_nonzero_trt_thresh"],
            n_nonzero_cntrl_thresh=case["n_nonzero_cntrl_thresh"],
        )
        np.testing.assert_allclose(
            got["power"].sum(),
            case["expected_num_discoveries"],
            rtol=RTOL,
            atol=ATOL,
            err_msg=f"case {case['label']}",
        )


def test_qc_thresholds_only_ever_reduce_power(perturbplan_ground_truth):
    """The QC factor is `1 - P(fail)`, so raising a threshold cannot raise power.

    Guards the direction of the `(1 - QC_prob)` multiplication, which is the
    one place in the port where an inverted sign would still produce
    plausible-looking probabilities.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_mean=0.85,
        fold_change_sd=0.13,
        cutoff=6.4840e-4 / 2,
        num_total_cells=gt["num_total_cells"],
        side="left",
    )
    no_qc = compute_power(
        pairs, cells_per_grna, baseline, n_nonzero_trt_thresh=0, n_nonzero_cntrl_thresh=0, **common
    )
    with_qc = compute_power(
        pairs, cells_per_grna, baseline, n_nonzero_trt_thresh=7, n_nonzero_cntrl_thresh=7, **common
    )
    assert (no_qc["qc_failure_prob"] == 0).all()
    assert (with_qc["power"] <= no_qc["power"] + 1e-15).all()
    # And it has to actually bite somewhere, or the test proves nothing: the 3-cell target cannot
    # clear a 7-nonzero-cell threshold.
    assert (with_qc["power"] < no_qc["power"]).any()


def test_num_trt_cells_is_the_sum_not_the_union(perturbplan_ground_truth):
    """The aggregation R performs, pinned against the union it is easily mistaken for.

    `many_grnas` has 20 gRNAs summing to 394 cells; the union of those cells
    in a real high-MOI screen would be smaller. Substituting it is a different
    estimator -- see `docs/design.md`.
    """
    gt = perturbplan_ground_truth
    _, cells_per_grna, _ = _frames(gt)
    agg = target_cell_counts(cells_per_grna).set_index("grna_target")
    raw = pd.DataFrame(gt["cells_per_grna"])
    for target, group in raw.groupby("grna_target"):
        n = group["num_cells"].to_numpy(dtype=float)
        assert agg.loc[target, "num_trt_cells"] == pytest.approx(n.sum())
        assert agg.loc[target, "num_trt_cells_sq"] == pytest.approx((n**2).sum())
    # A single-gRNA target is the one case where sum-of-squares equals the square of the sum, so
    # it cannot distinguish the two; a multi-gRNA target must.
    assert agg.loc["one_grna", "num_trt_cells_sq"] == agg.loc["one_grna", "num_trt_cells"] ** 2
    assert agg.loc["many_grnas", "num_trt_cells_sq"] < agg.loc["many_grnas", "num_trt_cells"] ** 2


def test_non_targeting_grnas_are_dropped():
    """`"non-targeting"` is not a target, and the complement group does not use it."""
    cells = pd.DataFrame(
        {
            "grna_id": ["a1", "a2", "ntc1", "ntc2"],
            "grna_target": ["A", "A", "non-targeting", "non-targeting"],
            "num_cells": [10, 20, 500, 600],
        }
    )
    agg = target_cell_counts(cells)
    assert agg["grna_target"].tolist() == ["A"]
    assert agg["num_trt_cells"].tolist() == [30.0]


def test_var_nb_and_zero_prob_are_the_r_expressions():
    """Two one-liners worth pinning, because both invite a plausible wrong form."""
    # var_nb takes the NB size (theta), so the quadratic term is mean^2/size, not mean^2*size.
    assert var_nb(np.array([2.0]), np.array([4.0]))[0] == pytest.approx(2.0 + 4.0 / 4.0)
    # zero_prob at size -> a Poisson limit: (s/(m+s))^s -> exp(-m) as s grows.
    big = zero_prob(1.0, np.array([1.5]), np.array([1e9]))[0]
    assert big == pytest.approx(np.exp(-1.5), rel=1e-6)


def test_missing_inputs_raise_rather_than_producing_nan(perturbplan_ground_truth):
    """A pair with no counts or no baseline stats must fail loudly.

    Left to a merge it would become a NaN power, indistinguishable in a result
    table from a pair that was scored and found hopeless.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_mean=0.85,
        fold_change_sd=0.13,
        cutoff=1e-4,
        num_total_cells=gt["num_total_cells"],
    )
    ghost_target = pd.DataFrame(
        {"grna_target": ["nowhere"], "response_id": [baseline["response_id"][0]]}
    )
    with pytest.raises(KeyError, match="cells_per_grna"):
        compute_power(ghost_target, cells_per_grna, baseline, **common)

    ghost_gene = pd.DataFrame(
        {"grna_target": [cells_per_grna["grna_target"][0]], "response_id": ["nosuchgene"]}
    )
    with pytest.raises(KeyError, match="baseline_expression_stats"):
        compute_power(ghost_gene, cells_per_grna, baseline, **common)


@pytest.mark.parametrize(
    ("kwargs", "match"),
    [
        ({"cutoff": 0.0}, "cutoff"),
        ({"cutoff": 1.0}, "cutoff"),
        ({"fold_change_mean": 0.15, "cutoff": 1e-4}, None),  # valid: an 85% knockdown
        ({"fold_change_mean": -0.5}, "multiplier"),
        ({"fold_change_sd": -0.1}, "fold_change_sd"),
        ({"side": "sideways"}, "side"),
        ({"n_nonzero_trt_thresh": -1}, "non-negative"),
    ],
)
def test_arguments_are_validated(perturbplan_ground_truth, kwargs, match):
    """Cheap guards, listed here so a future signature change cannot drop them silently."""
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_mean=0.85,
        fold_change_sd=0.13,
        cutoff=1e-4,
        num_total_cells=gt["num_total_cells"],
    )
    common.update(kwargs)
    if match is None:
        compute_power(pairs, cells_per_grna, baseline, **common)
        return
    with pytest.raises(ValueError, match=match):
        compute_power(pairs, cells_per_grna, baseline, **common)


def test_summed_treated_count_can_exceed_the_cell_count(perturbplan_ground_truth):
    """The consequence of summing rather than unioning, surfaced rather than hidden.

    In high MOI a cell carries several gRNAs, so the sum over a target's gRNAs
    can exceed the number of distinct cells -- and then the complement group
    goes empty. The error says so, because the cause is not guessable from a
    NaN.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    with pytest.raises(ValueError, match="not the union"):
        compute_power(
            pairs,
            cells_per_grna,
            baseline,
            fold_change_mean=0.85,
            fold_change_sd=0.13,
            cutoff=1e-4,
            num_total_cells=100,
        )


def test_a_stricter_threshold_never_raises_power(perturbplan_ground_truth):
    """The monotonicity in `cutoff`, which does hold everywhere.

    The two values are the trans and cis designs' measured thresholds --
    the comparison that made `cutoff` a required argument.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_mean=0.95,
        fold_change_sd=0.13,
        num_total_cells=gt["num_total_cells"],
        side="left",
    )
    cis = compute_power(pairs, cells_per_grna, baseline, cutoff=6.4840e-4 / 2, **common)
    trans = compute_power(pairs, cells_per_grna, baseline, cutoff=6.2252e-5 / 2, **common)
    assert (trans["power"] <= cis["power"]).all()
    assert (trans["power"] < cis["power"]).any()


def test_power_rises_with_effect_size_where_the_pair_is_testable(perturbplan_ground_truth):
    """The monotonicity a reader assumes, asserted only where it holds.

    Restricted to pairs with any appreciable power at the weaker effect size,
    because it is *not* a property of the closed form in general -- see the
    next test.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_sd=0.13,
        cutoff=6.4840e-4 / 2,
        num_total_cells=gt["num_total_cells"],
        side="left",
    )
    weak = compute_power(pairs, cells_per_grna, baseline, fold_change_mean=0.95, **common)
    strong = compute_power(pairs, cells_per_grna, baseline, fold_change_mean=0.50, **common)
    testable = weak["power"] > 1e-3
    assert testable.sum() >= 5, "the guard would make this test vacuous"
    assert (strong.loc[testable, "power"] >= weak.loc[testable, "power"]).all()
    assert (strong.loc[testable, "power"] > weak.loc[testable, "power"]).any()


def test_power_can_fall_with_effect_size_for_a_hopeless_pair(perturbplan_ground_truth):
    """A real non-monotonicity of the closed form, pinned so nobody "fixes" it.

    On a 3-cell target and a near-zero-expression gene, PerturbPlan's own R
    reports power *falling* as the knockdown deepens: 2.43e-4 at es = 0.05,
    1.19e-4 at 0.15, 1.09e-6 at 0.50. A deeper knockdown lowers the treated
    group's negative-binomial variance, and with the statistic's mean still
    ~3.3 sd short of a threshold that far out, concentrating it moves mass
    *away* from the rejection region rather than into it.

    It is confined to pairs whose power is ~0 under every effect size, so it
    changes no decision, and the R does the same thing -- which is the point:
    the port reproduces the estimator that was validated, corners included.
    See `docs/design.md`, "Analytical per-pair power".
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    hopeless = pairs[
        (pairs["grna_target"] == "tiny_trt") & (pairs["response_id"] == "gene_low")
    ].reset_index(drop=True)
    common = dict(
        fold_change_sd=0.13,
        cutoff=6.4840e-4 / 2,
        num_total_cells=gt["num_total_cells"],
        side="left",
    )
    curve = [
        compute_power(hopeless, cells_per_grna, baseline, fold_change_mean=1 - es, **common)[
            "power"
        ].iloc[0]
        for es in (0.05, 0.15, 0.50)
    ]
    assert curve[0] > curve[1] > curve[2]
    # And it only happens where nothing was detectable anyway.
    assert max(curve) < 1e-3


def test_power_is_a_probability(perturbplan_ground_truth):
    """Over every case in the fixture, including the far-tail ones."""
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    for case in gt["cases"]:
        got = compute_power(
            pairs,
            cells_per_grna,
            baseline,
            fold_change_mean=case["fold_change_mean"],
            fold_change_sd=case["fold_change_sd"],
            cutoff=case["cutoff"],
            num_total_cells=gt["num_total_cells"],
            side=case["side"],
            n_nonzero_trt_thresh=case["n_nonzero_trt_thresh"],
            n_nonzero_cntrl_thresh=case["n_nonzero_cntrl_thresh"],
        )
        assert got["power"].between(0.0, 1.0).all(), case["label"]
        assert np.isfinite(got["power"]).all(), case["label"]


def test_duplicate_keys_raise(perturbplan_ground_truth):
    """R's joins use `relationship = "many-to-one"`, which errors on a repeated key.

    Silently taking the first row would pick a gene's statistics arbitrarily,
    and a repeated gRNA would be counted twice into its target's summed cell
    count -- a wrong number, not a missing one.
    """
    gt = perturbplan_ground_truth
    pairs, cells_per_grna, baseline = _frames(gt)
    common = dict(
        fold_change_mean=0.85,
        fold_change_sd=0.13,
        cutoff=1e-4,
        num_total_cells=gt["num_total_cells"],
    )
    dup_gene = pd.concat([baseline, baseline.iloc[[0]]], ignore_index=True)
    with pytest.raises(ValueError, match="duplicated response_id"):
        compute_power(pairs, cells_per_grna, dup_gene, **common)

    dup_grna = pd.concat([cells_per_grna, cells_per_grna.iloc[[0]]], ignore_index=True)
    with pytest.raises(ValueError, match="repeats 1"):
        compute_power(pairs, dup_grna, baseline, **common)


def test_a_guide_shared_by_two_targets_is_counted_into_both(perturbplan_ground_truth):
    """The gRNA-to-target map is many-to-many, and R sums a shared guide into every target.

    Overlapping candidate elements share guides: on one real screen 1,673 of
    43,736 sit inside two or three, so the same `grna_id` appears under
    several targets. Deduplicating by `grna_id` would look like sensible
    hygiene and would silently shrink those targets. The fixture carries
    `shared_a` and `shared_b`, which share `g_shared_2`.
    """
    gt = perturbplan_ground_truth
    _, cells_per_grna, _ = _frames(gt)
    shared = cells_per_grna[cells_per_grna["grna_id"] == "g_shared_2"]
    assert set(shared["grna_target"]) == {"shared_a", "shared_b"}, "fixture lost the shared guide"

    agg = target_cell_counts(cells_per_grna).set_index("grna_target")
    # 40 + 60 and 60 + 75: the shared guide's 60 cells count into both.
    assert agg.loc["shared_a", "num_trt_cells"] == pytest.approx(100.0)
    assert agg.loc["shared_b", "num_trt_cells"] == pytest.approx(135.0)
    # And the power for both targets matches R, which is what actually settles it.
    assert any(t in ("shared_a", "shared_b") for t in gt["cases"][0]["grna_target"])
