"""Low MOI against R: sceptre's own numbers for the NT-cells path, value for value.

The fixture is `lowmoi_ground_truth.json`, from `scripts/dump_lowmoi_ground_truth.R`
on sceptre's simulated example data. Permutation p-values are compared exactly by
handing pysceptre R's own draws, regenerated by `r_samplers`, a test-only replica of
R's two permutation samplers that is itself checked against R's draws first. CRT
draws are not replicated, so for the CRT only the deterministic parts -- fits, fold
changes, statistics, pairwise QC -- are compared value for value.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from r_samplers import fisher_yates_samlper, hybrid_fisher_iwor_sampler
from scipy import sparse, stats

from pysceptre import run_calibration_check, run_discovery_analysis, run_power_check
from pysceptre.glm.irls import fit_binomial_glm_batch, fit_poisson_glm_batch
from pysceptre.glm.nb_theta import estimate_theta
from pysceptre.pipeline.api import nt_cell_pool
from pysceptre.pipeline.discovery import (
    combined_cells,
    run_discovery_nt_cells,
    run_discovery_ntcells_complement,
)
from pysceptre.pipeline.pairwise_qc import nonzero_counts
from pysceptre.precompute.pieces import compute_precomputation_pieces
from pysceptre.test_statistic.resampling import run_low_level_test_full
from pysceptre.test_statistic.score_stat import PermutationSliceDraws

B1, B2, B3 = 499, 4999, 24999
B_PERM = B1 + B2 + B3


def _replica(spec: dict) -> np.ndarray:
    """R's draws for a recorded sampler call."""
    if spec["sampler"] == "fisher_yates":
        return fisher_yates_samlper(spec["n_tot"], spec["M"], spec["B"])
    return hybrid_fisher_iwor_sampler(spec["N"], spec["m"], spec["M"], spec["B"])


def _frame(table: dict) -> pd.DataFrame:
    return pd.DataFrame(table)


# --- the replica is R's samplers ----------------------------------------------------------


def test_the_replica_reproduces_rs_small_sampler_calls(lowmoi_ground_truth):
    s = lowmoi_ground_truth["samplers"]
    for case in s["fisher_yates"]:
        got = fisher_yates_samlper(case["n_tot"], case["M"], case["B"])
        np.testing.assert_array_equal(got, np.array(case["draws_0based"]).reshape(got.shape))
    for case in s["hybrid_fisher_iwor"]:
        got = hybrid_fisher_iwor_sampler(case["N"], case["m"], case["M"], case["B"])
        np.testing.assert_array_equal(got, np.array(case["draws_0based"]).reshape(got.shape))


def test_the_replica_reproduces_every_full_size_call_used_below(lowmoi_ground_truth):
    for pin in lowmoi_ground_truth["samplers"]["pins"]:
        spec = dict(pin["args"], sampler=pin["sampler"])
        draws = _replica(spec)
        rows = np.array(pin["draw_index_0based"])
        np.testing.assert_array_equal(draws[rows], np.array(pin["draws_0based"]))
        assert int(draws.sum()) == pin["sum_entries"]
        weights = np.arange(1, draws.shape[1] + 1)
        assert int((draws * weights).sum()) == pin["sum_position_weighted"]


# --- one pair at a time: the NT-cells internals --------------------------------------------


@pytest.fixture(scope="module")
def unit(lowmoi_ground_truth):
    u = lowmoi_ground_truth["unit"]
    X = np.array(u["X"], dtype=float)
    genes = {g["gene_id"]: np.array(g["y"], dtype=float) for g in u["genes"]}
    targets = {t["target_id"]: t for t in u["targets"]}
    ntc = {g["grna_id"]: np.array(g["cells_0based"]) for g in u["nt_grnas"]}
    pool = nt_cell_pool(ntc, X.shape[0])
    perms = _replica(u["permutation_sampler"])
    return u, X, genes, targets, ntc, pool, perms


def _pair_pieces(X, y, cells):
    fit = fit_poisson_glm_batch(X[cells], y[cells])
    theta, _ = estimate_theta(y=y[cells], mu=fit.fitted_values, dfr=cells.size - X.shape[1])
    theta = min(max(theta, 0.01), 1000.0)
    return fit, theta, compute_precomputation_pieces(y[cells], X[cells], fit.coefs, theta)


def test_the_nt_pool_and_combined_cells_are_rs(unit):
    u, X, genes, targets, ntc, pool, perms = unit
    np.testing.assert_array_equal(pool, u["all_nt_idxs_0based"])
    for t in targets.values():
        np.testing.assert_array_equal(
            combined_cells(np.array(t["cells_0based"]), pool), t["combined_cells_0based"]
        )


def test_each_pair_is_fit_as_r_fits_it(unit):
    u, X, genes, targets, ntc, pool, perms = unit
    for pair in u["pairs"]:
        cells = np.array(targets[pair["target_id"]]["combined_cells_0based"])
        fit, theta, pieces = _pair_pieces(X, genes[pair["gene_id"]], cells)
        np.testing.assert_allclose(fit.coefs, pair["fitted_coefs"], rtol=1e-6, atol=1e-8)
        np.testing.assert_allclose(theta, pair["theta"], rtol=1e-4)
        for name in ("mu", "w", "a"):
            np.testing.assert_allclose(
                getattr(pieces, name), pair[name], rtol=1e-6, atol=1e-8, err_msg=name
            )


def test_each_targets_logistic_fit_on_its_combined_cells_is_rs(unit):
    u, X, genes, targets, ntc, pool, perms = unit
    for t in targets.values():
        cells = np.array(t["combined_cells_0based"])
        indicator = np.zeros(cells.size)
        indicator[: t["n_trt"]] = 1.0
        fitted = fit_binomial_glm_batch(X[cells], indicator).fitted_values
        np.testing.assert_allclose(fitted, t["logistic_fitted_probabilities"], rtol=1e-6, atol=1e-8)


def _check(result, r, *, p=True):
    if p:
        assert result.stage == r["stage"]
    np.testing.assert_allclose(result.z_orig, r["z_orig"], rtol=1e-5)
    np.testing.assert_allclose(result.fold_change, r["fc"], rtol=1e-6)
    np.testing.assert_allclose(result.se_fold_change, r["se_over_root_n"], rtol=1e-6)
    if p:
        np.testing.assert_allclose(result.p_value, r["p"], rtol=1e-6, atol=1e-12)


@pytest.mark.parametrize("variant", ["perm", "perm_no_approximation", "crt"])
def test_each_pairs_test_on_rs_own_draws_is_rs(unit, variant):
    """The staged test on R's permutation draws reproduces R's p-value; under the
    CRT the draws differ, so only the statistic and fold change are compared."""
    u, X, genes, targets, ntc, pool, perms = unit
    for pair in u["pairs"]:
        cells = np.array(targets[pair["target_id"]]["combined_cells_0based"])
        y = genes[pair["gene_id"]][cells]
        _, _, pieces = _pair_pieces(X, genes[pair["gene_id"]], cells)
        n_trt = pair["n_trt"]
        r = pair[variant]
        draws = PermutationSliceDraws(perms, n_trt, cells.size)
        result = run_low_level_test_full(
            y,
            pieces.mu,
            pieces.a,
            pieces.w,
            pieces.D,
            np.arange(n_trt),
            draws,
            B1=r["B1"],
            B2=r["B2"],
            B3=r["B3"],
            fit_parametric_curve=variant != "perm_no_approximation",
            side_code=u["side_code"],
        )
        _check(result, r, p=variant != "crt")


def test_the_engine_on_rs_draws_reproduces_every_unit_pair(unit):
    """`run_discovery_nt_cells` end to end -- pool order, combined cells, fits,
    staging -- against R's `discovery_ntcells_perm_test`."""
    u, X, genes, targets, ntc, pool, perms = unit
    gene_ids = list(genes)
    response = np.stack([genes[g] for g in gene_ids])
    pairs = pd.DataFrame(
        {
            "response_id": [p["gene_id"] for p in u["pairs"]],
            "grna_target": [p["target_id"] for p in u["pairs"]],
        }
    )
    result = run_discovery_nt_cells(
        response,
        gene_ids,
        X,
        {t: np.array(v["cells_0based"]) for t, v in targets.items()},
        pool,
        pairs,
        B1=B1,
        B2=B2,
        B3=B3,
        side_code=u["side_code"],
        resampling_mechanism="permutations",
        permutations=perms,
    ).set_index(["response_id", "grna_target"])
    for pair in u["pairs"]:
        row = result.loc[(pair["gene_id"], pair["target_id"])]
        r = pair["perm"]
        assert row["stage"] == r["stage"]
        np.testing.assert_allclose(row["p_value"], r["p"], rtol=1e-6, atol=1e-12)
        np.testing.assert_allclose(row["z_orig"], r["z_orig"], rtol=1e-5)
        np.testing.assert_allclose(row["fold_change"], r["fc"], rtol=1e-6)


def test_the_calibration_on_the_nt_cells_is_rs(unit):
    """R restricts the universe to the NT pool: fits on the pool, positions in it."""
    u, X, genes, targets, ntc, pool, perms = unit
    c = u["calibration"]
    np.testing.assert_array_equal(pool, c["nt_pool_cells_0based"])
    Xn = X[pool]
    pieces = {}
    for gene in c["genes"]:
        y = genes[gene["gene_id"]][pool]
        fit, theta, p = _pair_pieces(Xn, y, np.arange(pool.size))
        np.testing.assert_allclose(fit.coefs, gene["fitted_coefs"], rtol=1e-6, atol=1e-8)
        np.testing.assert_allclose(theta, gene["theta"], rtol=1e-4)
        np.testing.assert_allclose(p.mu, gene["mu"], rtol=1e-6, atol=1e-8)
        pieces[gene["gene_id"]] = (y, p)
    position = {int(cell): i for i, cell in enumerate(pool)}
    groups = {}
    for group in c["groups"]:
        members = group["grna_group"].split("&")
        trt = np.sort([position[int(x)] for m in members for x in ntc[m]])
        np.testing.assert_array_equal(trt, np.sort(group["trt_positions_0based"]))
        groups[group["grna_group"]] = np.array(group["trt_positions_0based"])
    fy = _replica(c["permutation_sampler"])
    for pair in c["pairs"]:
        y, p = pieces[pair["gene_id"]]
        trt = groups[pair["grna_group"]]
        r = pair["perm"]
        result = run_low_level_test_full(
            y,
            p.mu,
            p.a,
            p.w,
            p.D,
            trt,
            PermutationSliceDraws(fy, pair["n_trt"], pool.size),
            B1=r["B1"],
            B2=r["B2"],
            B3=r["B3"],
            fit_parametric_curve=True,
            side_code=u["side_code"],
        )
        _check(result, r)


# --- sceptre's whole low-MOI pipeline, on its simulated example ----------------------------


@pytest.fixture(scope="module")
def example(lowmoi_ground_truth):
    e = lowmoi_ground_truth["end_to_end"]
    response = sparse.csr_matrix(np.array(e["response_matrix"], dtype=float))
    X = np.array(e["covariate_matrix"], dtype=float)
    a = e["grna_assignments"]
    targets = {t: np.array(c) for t, c in a["targets"].items()}
    ntc = {g: np.array(c) for g, c in a["nt_grnas"].items()}
    return e, response, list(e["response_ids"]), X, targets, ntc


def _grid(e, control_group, mechanism):
    (cell,) = [
        g
        for g in e["grid"]
        if g["control_group"] == control_group and g["resampling_mechanism"] == mechanism
    ]
    return cell


GRID = [
    ("nt_cells", "permutations"),
    ("nt_cells", "crt"),
    ("complement", "permutations"),
    ("complement", "crt"),
]


def test_the_example_nt_pool_is_rs(example):
    e, response, gene_ids, X, targets, ntc = example
    np.testing.assert_array_equal(
        nt_cell_pool(ntc, X.shape[0]), e["grna_assignments"]["all_nt_idxs_0based"]
    )


@pytest.mark.parametrize("control_group", ["nt_cells", "complement"])
def test_pairwise_qc_counts_are_rs_exactly(example, control_group):
    """The deterministic checkpoint: every pair's nonzero counts, before any test."""
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, "permutations")
    pool = nt_cell_pool(ntc, X.shape[0]) if control_group == "nt_cells" else None
    row = {g: i for i, g in enumerate(gene_ids)}
    for table in ("discovery_pairs_with_info", "positive_control_pairs_with_info"):
        info = _frame(cell[table])
        names = list(dict.fromkeys(info["grna_group"]))
        trt, cntrl = nonzero_counts(
            response, [targets[t] for t in names], X.shape[0], control_cells=pool
        )
        col = {t: j for j, t in enumerate(names)}
        r_idx = info["response_id"].map(row).to_numpy()
        c_idx = info["grna_group"].map(col).to_numpy()
        np.testing.assert_array_equal(trt[r_idx, c_idx], info["n_nonzero_trt"])
        np.testing.assert_array_equal(cntrl[r_idx, c_idx], info["n_nonzero_cntrl"])
        passed = (trt[r_idx, c_idx] >= cell["n_nonzero_trt_thresh"]) & (
            cntrl[r_idx, c_idx] >= cell["n_nonzero_cntrl_thresh"]
        )
        np.testing.assert_array_equal(passed, info["pass_qc"])

    neg = _frame(cell["negative_control_pairs"])
    universe = pool if pool is not None else np.arange(X.shape[0])
    position = np.full(X.shape[0], -1)
    position[universe] = np.arange(universe.size)
    sub = response[:, universe]
    names = list(dict.fromkeys(neg["grna_group"]))
    groups = [
        np.unique(np.concatenate([position[ntc[m]] for m in name.split("&")])) for name in names
    ]
    trt, cntrl = nonzero_counts(sub, groups, universe.size)
    col = {t: j for j, t in enumerate(names)}
    r_idx = neg["response_id"].map(row).to_numpy()
    c_idx = neg["grna_group"].map(col).to_numpy()
    np.testing.assert_array_equal(trt[r_idx, c_idx], neg["n_nonzero_trt"])
    np.testing.assert_array_equal(cntrl[r_idx, c_idx], neg["n_nonzero_cntrl"])


def _compare(ours: pd.DataFrame, r_table: dict, *, p_exact: bool):
    """Fold change and statistic always; p-values when both sides used R's draws."""
    r = _frame(r_table)
    r = r[r["pass_qc"].astype(bool)] if "pass_qc" in r else r
    merged = r.merge(ours, on=["response_id", "grna_target"], suffixes=("_r", ""))
    assert len(merged) == len(r)
    np.testing.assert_allclose(
        np.log2(merged["fold_change"]), merged["log_2_fold_change"], rtol=1e-6, atol=1e-9
    )
    np.testing.assert_allclose(merged["z_orig"], merged["z_orig_r"], rtol=1e-5, atol=1e-9)
    if p_exact:
        np.testing.assert_array_equal(merged["stage"], merged["stage_r"])
        np.testing.assert_allclose(merged["p_value"], merged["p_value_r"], rtol=1e-6, atol=1e-12)
    return merged


@pytest.mark.parametrize(("control_group", "mechanism"), GRID)
def test_discovery_through_the_public_api(example, control_group, mechanism):
    """pysceptre's own draws: deterministic parts exact, p-values close to R's."""
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, mechanism)
    info = _frame(cell["discovery_pairs_with_info"])
    pairs = info.loc[info["pass_qc"], ["response_id", "grna_group"]].rename(
        columns={"grna_group": "grna_target"}
    )
    ours = run_discovery_analysis(
        response,
        gene_ids,
        X,
        targets,
        pairs.reset_index(drop=True),
        moi="low",
        control_group=control_group,
        resampling_mechanism=mechanism,
        ntc_grna_cells=ntc if control_group == "nt_cells" else None,
        seed=0,
    )
    merged = _compare(ours, cell["discovery_result"], p_exact=False)
    assert stats.spearmanr(merged["p_value"], merged["p_value_r"]).statistic > 0.95


@pytest.mark.parametrize("control_group", ["nt_cells", "complement"])
def test_discovery_on_rs_draws_is_rs_value_for_value(example, control_group):
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, "permutations")
    info = _frame(cell["discovery_pairs_with_info"])
    pairs = info.loc[info["pass_qc"], ["response_id", "grna_group"]].rename(
        columns={"grna_group": "grna_target"}
    )
    common = dict(
        B1=B1,
        B2=B2,
        B3=B3,
        side_code=cell["side_code"],
        resampling_mechanism="permutations",
        permutations=_replica(cell["permutation_samplers"]["discovery"]),
    )
    if control_group == "nt_cells":
        ours = run_discovery_nt_cells(
            response, gene_ids, X, targets, nt_cell_pool(ntc, X.shape[0]), pairs, **common
        )
    else:
        ours = run_discovery_ntcells_complement(response, gene_ids, X, targets, pairs, **common)
    _compare(ours, cell["discovery_result"], p_exact=True)


@pytest.mark.parametrize(("control_group", "mechanism"), GRID)
def test_power_check_through_the_public_api(example, control_group, mechanism):
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, mechanism)
    pc = _frame(cell["positive_control_pairs_with_info"]).rename(
        columns={"grna_group": "grna_target"}
    )
    ours = run_power_check(
        response,
        gene_ids,
        X,
        targets,
        positive_control_pairs=pc[["response_id", "grna_target"]],
        moi="low",
        control_group=control_group,
        resampling_mechanism=mechanism,
        ntc_grna_cells=ntc if control_group == "nt_cells" else None,
        seed=0,
    )
    r = _frame(cell["power_result"])
    merged = r.merge(ours, on=["response_id", "grna_target"], suffixes=("_r", ""))
    assert len(merged) == len(r)
    np.testing.assert_array_equal(merged["n_nonzero_trt"], merged["n_nonzero_trt_r"])
    np.testing.assert_array_equal(merged["n_nonzero_cntrl"], merged["n_nonzero_cntrl_r"])
    np.testing.assert_array_equal(merged["pass_qc"], merged["pass_qc_r"])
    _compare(ours.dropna(subset=["p_value"]), cell["power_result"], p_exact=False)


@pytest.mark.parametrize(("control_group", "mechanism"), GRID)
def test_calibration_check_through_the_public_api(example, control_group, mechanism):
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, mechanism)
    neg = _frame(cell["negative_control_pairs"]).rename(columns={"grna_group": "grna_target"})
    ours = run_calibration_check(
        response,
        gene_ids,
        X,
        ntc,
        n_calibration_pairs=len(neg),
        calibration_group_size=cell["calibration_group_size"],
        negative_control_pairs=neg[["response_id", "grna_target"]],
        moi="low",
        control_group=control_group,
        resampling_mechanism=mechanism,
        seed=0,
    )
    merged = _compare(ours, cell["calibration_result"], p_exact=False)
    assert stats.spearmanr(merged["p_value"], merged["p_value_r"]).statistic > 0.95


@pytest.mark.parametrize("control_group", ["nt_cells", "complement"])
def test_calibration_on_rs_draws_is_rs_value_for_value(example, control_group):
    """With R's pairs and R's draws, the calibration check is R's, including the
    restriction to the NT cells and R's width rule for the shared draws."""
    e, response, gene_ids, X, targets, ntc = example
    cell = _grid(e, control_group, "permutations")
    neg = _frame(cell["negative_control_pairs"]).rename(columns={"grna_group": "grna_target"})
    n_cells = X.shape[0]
    universe = nt_cell_pool(ntc, n_cells) if control_group == "nt_cells" else np.arange(n_cells)
    position = np.full(n_cells, -1)
    position[universe] = np.arange(universe.size)
    groups = {
        name: np.unique(np.concatenate([position[ntc[m]] for m in name.split("&")]))
        for name in dict.fromkeys(neg["grna_target"])
    }
    spec = cell["permutation_samplers"]["calibration"]
    sizes = sorted((len(c) for c in ntc.values()), reverse=True)
    assert spec["M"] == sum(sizes[: cell["calibration_group_size"]])
    ours = run_discovery_ntcells_complement(
        response[:, universe],
        gene_ids,
        X[universe],
        groups,
        neg[["response_id", "grna_target"]],
        B1=B1,
        B2=B2,
        B3=B3,
        side_code=cell["side_code"],
        resampling_mechanism="permutations",
        permutations=_replica(spec),
    )
    _compare(ours, cell["calibration_result"], p_exact=True)
