#!/usr/bin/env python3
"""Compare pysceptre with R sceptre on sceptredata's two real example screens.

    scripts/compare_sceptredata.py <dir> [<dir> ...] [--json PATH]
                                   [--n-jobs 1 8] [--pin-samplers]

A <dir> is one run written by `scripts/run_sceptredata_examples.R`, that is
`<out_dir>/<dataset>/<control_group>_<mechanism>/` holding `run_info.json`,
R's three result CSVs and `export/dataset.h5mu`, or that script's `<out_dir>`,
which stands for every run under it. The export comes from
`scripts/export_sceptre_dataset.R` followed by `scripts/make_h5mu.py`.

Both sides test the same pairs: discovery on R's `pass_qc` pairs, the power
check on every positive control R reports, and the calibration check on R's
negative control pairs with R's group size and QC thresholds. Four kinds of
comparison follow:

  deterministic  per-pair nonzero counts and `pass_qc` (every discovery pair,
                 the calibration pairs, the power check), fold change and
                 `z_orig`, none of which resampling enters
  own RNG        pysceptre's own draws at seed 0: p-value rank and log-scale
                 agreement, BH calls at R's alpha, calibration uniformity
  R's draws      permutation runs only: R's shared permutation draws,
                 regenerated by `tests/validation/r_samplers.py` and handed to
                 the low-level entry points with the cells in R's order, so
                 p-values compare value for value. Stage-2 p-values are also
                 checked against an independent evaluation of the skew-normal
                 tail at R's own fit (`stage_2_against_reference`), which says
                 which side is off when the two disagree
  wall time      pysceptre at each `--n-jobs`, next to R's from run_info.json

`--pin-samplers` first asks R for its own draws (sceptre's
`get_synthetic_permutation_idxs` on `sceptre_object.rds`) and checks the
replica against them over every draw: entry sum, position-weighted sum and a
few whole rows.

R's CSVs are read with `float_precision="round_trip"`; pandas' default parser
is off by a few ulp on them.

Results are merged into `--json` (default `<out_dir>/comparison.json`) under
`<dataset>/<run>`, and a summary is printed, ending in a Markdown table built
from everything in the JSON. The JSON is derived from real data, so it is
refused a path inside a git work tree that git does not ignore.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import platform
import subprocess
import sys
import tempfile
import time
import warnings
from collections import Counter
from datetime import datetime
from importlib import metadata
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import integrate, special, stats
from scipy.stats import skewnorm

import pysceptre
from pysceptre.pipeline.api import (
    nt_cell_pool,
    run_calibration_check,
    run_discovery_analysis,
    run_power_check,
)
from pysceptre.pipeline.calibration import negative_control_pairs_from_names
from pysceptre.pipeline.discovery import run_discovery_nt_cells, run_discovery_ntcells_complement
from pysceptre.pipeline.pairwise_qc import nonzero_counts

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO / "tests" / "validation"))

from r_samplers import fisher_yates_samlper, hybrid_fisher_iwor_sampler  # noqa: E402
from sceptre_io import load_export  # noqa: E402

# R's order of the three analyses in run_sceptredata_examples.R.
ANALYSES = ("calibration", "power", "discovery")
CSV = {
    "calibration": "run_calibration_check.csv",
    "power": "run_power_check.csv",
    "discovery": "run_discovery_analysis.csv",
}
R_STEP = {
    "calibration": "run_calibration_check",
    "power": "run_power_check",
    "discovery": "run_discovery_analysis",
}
KEY = ["response_id", "grna_target"]
SIDE_CODES = {"left": -1, "both": 0, "right": 1}
# Draws compared row for row when the replica is pinned against R.
PINNED_DRAWS = (0, 1, 2, 499, 5498, 30496)
SEED = 0

_PIN_R = r"""
suppressPackageStartupMessages(library(sceptre))
args <- commandArgs(trailingOnly = TRUE)
so <- readRDS(args[[1]])
pins <- as.integer(strsplit(args[[2]], ",")[[1]])
ns <- asNamespace("sceptre")
B <- so@B1 + so@B2 + so@B3
out <- list()
for (cal in c(TRUE, FALSE)) {
  ptr <- get("get_synthetic_permutation_idxs", envir = ns)(
    grna_assignments = so@grna_assignments, B = B, calibration_check = cal,
    control_group_complement = so@control_group_complement,
    calibration_group_size = so@calibration_group_size, n_cells = length(so@cells_in_use))
  d <- lapply(get("synth_idx_list_to_r_list", envir = ns)(ptr), as.integer)
  out[[if (cal) "calibration" else "discovery"]] <- list(
    B = length(d), width = length(d[[1]]),
    sum_entries = sprintf("%.0f", sum(vapply(d, function(v) sum(as.numeric(v)), numeric(1)))),
    sum_position_weighted = sprintf("%.0f",
      sum(vapply(d, function(v) sum(as.numeric(v) * seq_along(v)), numeric(1)))),
    pinned_rows = lapply(pins[pins < length(d)], function(i) d[[i + 1L]]))
}
cat(jsonlite::toJSON(out, auto_unbox = TRUE))
"""


# --- input --------------------------------------------------------------------------------


def find_runs(paths: list[Path]) -> list[Path]:
    """Run directories: each given one, or every run under a given out_dir."""
    runs: list[Path] = []
    for path in paths:
        if (path / "run_info.json").exists():
            runs.append(path)
            continue
        found = sorted(p.parent for p in path.glob("*/*/run_info.json"))
        if not found:
            raise SystemExit(f"{path}: neither a run directory nor an out_dir holding runs")
        runs.extend(found)
    return runs


def run_key(run_dir: Path) -> str:
    return f"{run_dir.parent.name}/{run_dir.name}"


def read_r(run_dir: Path, analysis: str) -> pd.DataFrame:
    """R's whole result table, exactly as written."""
    return pd.read_csv(run_dir / CSV[analysis], float_precision="round_trip")


def r_tested(r: pd.DataFrame) -> pd.DataFrame:
    """R's rows that were tested, with `stage` and `significant` as plain types."""
    out = r[r["pass_qc"].astype(bool)].copy()
    out["stage"] = out["stage"].astype(int)
    if "significant" in out:
        out["significant"] = out["significant"].astype(bool)
    return out.reset_index(drop=True)


def check_settings(e, info: dict) -> dict:
    """The export's settings, checked against what R recorded for the run."""
    s = info["settings"]
    kwargs = e.analysis_kwargs()
    meta = e.metadata
    problems = []
    for k in ("moi", "control_group", "resampling_mechanism", "side"):
        if kwargs[k] != s[k]:
            problems.append(f"{k}: export {kwargs[k]!r}, R {s[k]!r}")
    for k in ("B1", "B2", "B3", "n_nonzero_trt_thresh", "n_nonzero_cntrl_thresh"):
        if meta[k] != s[k]:
            problems.append(f"{k}: export {meta[k]!r}, R {s[k]!r}")
    if meta["calibration_group_size"] != s["calibration_group_size"]:
        problems.append(
            f"calibration_group_size: export {meta['calibration_group_size']}, "
            f"R {s['calibration_group_size']}"
        )
    if e.covariate_matrix.shape[0] != s["n_cells_in_use"]:
        problems.append(f"cells: export {e.covariate_matrix.shape[0]}, R {s['n_cells_in_use']}")
    if list(meta["covariate_names"]) != list(s["covariate_matrix_columns"]):
        problems.append("covariate columns differ")
    if problems:
        raise SystemExit("export does not match the R run: " + "; ".join(problems))
    return {
        "moi": kwargs["moi"],
        "control_group": kwargs["control_group"],
        "resampling_mechanism": kwargs["resampling_mechanism"],
        "side": kwargs["side"],
        "resampling_approximation": kwargs.get("resampling_approximation", "skew_normal"),
        "multiple_testing_alpha": kwargs.get("multiple_testing_alpha", 0.1),
        "B1": meta["B1"],
        "B2": meta["B2"],
        "B3": meta["B3"],
        "n_nonzero_trt_thresh": meta["n_nonzero_trt_thresh"],
        "n_nonzero_cntrl_thresh": meta["n_nonzero_cntrl_thresh"],
        "calibration_group_size": s["calibration_group_size"],
        "n_genes": len(e.gene_ids),
        "n_cells": int(e.covariate_matrix.shape[0]),
        "n_covariates": int(e.covariate_matrix.shape[1]),
        "n_targets_with_cells": len(e.grna_target_cells),
        "n_ntc_grnas": len(e.ntc_grna_cells or {}),
    }


# --- pysceptre runs ------------------------------------------------------------------------


def timed(fn):
    """`fn()`, its wall time, and the warnings it raised, tallied by message."""
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        start = time.perf_counter()
        out = fn()
        elapsed = time.perf_counter() - start
    tally = Counter(str(w.message)[:400] for w in caught)
    return out, elapsed, [{"message": m, "count": c} for m, c in tally.items()]


def run_own(analysis: str, e, r: pd.DataFrame, settings: dict, n_jobs: int) -> pd.DataFrame:
    """One analysis through the public API, with pysceptre's own draws."""
    kwargs = e.analysis_kwargs()
    thresholds = dict(
        n_nonzero_trt_thresh=settings["n_nonzero_trt_thresh"],
        n_nonzero_cntrl_thresh=settings["n_nonzero_cntrl_thresh"],
    )
    if analysis == "discovery":
        pairs = r.loc[r["pass_qc"].astype(bool), KEY].reset_index(drop=True)
        return run_discovery_analysis(
            e.response_matrix,
            e.gene_ids,
            e.covariate_matrix,
            e.grna_target_cells,
            pairs,
            **kwargs,
            seed=SEED,
            n_jobs=n_jobs,
        )
    if analysis == "power":
        return run_power_check(
            e.response_matrix,
            e.gene_ids,
            e.covariate_matrix,
            e.grna_target_cells,
            positive_control_pairs=r[KEY].reset_index(drop=True),
            **thresholds,
            **kwargs,
            seed=SEED,
            n_jobs=n_jobs,
        )
    kwargs.pop("ntc_grna_cells", None)
    pairs = r[KEY].reset_index(drop=True)
    return run_calibration_check(
        e.response_matrix,
        e.gene_ids,
        e.covariate_matrix,
        e.ntc_grna_cells,
        n_calibration_pairs=len(pairs),
        calibration_group_size=settings["calibration_group_size"],
        negative_control_pairs=pairs,
        **thresholds,
        **kwargs,
        seed=SEED,
        n_jobs=n_jobs,
    )


def calibration_universe(e, pool: np.ndarray | None) -> np.ndarray:
    """The cells a calibration check runs on: the NT pool, or every cell."""
    return pool if pool is not None else np.arange(e.covariate_matrix.shape[0])


def calibration_groups(e, pairs: pd.DataFrame, universe: np.ndarray) -> dict[str, np.ndarray]:
    """Each synthetic group's cells, as positions in `universe`."""
    n_cells = e.covariate_matrix.shape[0]
    position = np.full(n_cells, -1, dtype=np.int64)
    position[universe] = np.arange(universe.size)
    ntc = {g: position[np.asarray(c, dtype=np.int64)] for g, c in e.ntc_grna_cells.items()}
    return negative_control_pairs_from_names(pairs, ntc, universe.size)


def sampler_specs(e, settings: dict, pool: np.ndarray | None) -> dict:
    """R's shared permutation sampler calls, sized from the export.

    `discovery` serves discovery and the power check; `calibration` the
    calibration check. Both follow sceptre's `get_synthetic_permutation_idxs`.
    """
    B = settings["B1"] + settings["B2"] + settings["B3"]
    sizes = [len(c) for c in e.grna_target_cells.values() if len(c)]
    nt_sizes = sorted((len(c) for c in e.ntc_grna_cells.values() if len(c)), reverse=True)
    width = int(sum(nt_sizes[: settings["calibration_group_size"]]))
    if pool is None:
        n = settings["n_cells"]
        discovery = {"sampler": "fisher_yates", "n_tot": n, "M": max(sizes), "B": B}
        calibration = {"sampler": "fisher_yates", "n_tot": n, "M": width, "B": B}
    else:
        discovery = {
            "sampler": "hybrid_fisher_iwor",
            "N": int(pool.size),
            "m": min(sizes),
            "M": max(sizes),
            "B": B,
        }
        calibration = {"sampler": "fisher_yates", "n_tot": int(pool.size), "M": width, "B": B}
    return {"discovery": discovery, "calibration": calibration}


def check_specs_against_r(specs: dict, info: dict, pool: np.ndarray | None) -> list[str]:
    """Where the derived sizing disagrees with the sizes R recorded for the run."""
    s = info["settings"]
    problems = []
    disc = specs["discovery"]
    lo, hi = s["grna_group_n_cells_range"]
    if disc["M"] != hi or (pool is not None and disc["m"] != lo):
        problems.append(f"target size range {disc.get('m')}..{disc['M']}, R {lo}..{hi}")
    if pool is not None and pool.size != s["n_nt_cells"]:
        problems.append(f"NT pool {pool.size} cells, R {s['n_nt_cells']}")
    nt_sizes = sorted(s["indiv_nt_grna_n_cells"].values(), reverse=True)
    width = sum(nt_sizes[: s["calibration_group_size"]])
    if specs["calibration"]["M"] != width:
        problems.append(f"calibration width {specs['calibration']['M']}, R's sizes give {width}")
    return problems


def make_draws(spec: dict) -> np.ndarray:
    if spec["sampler"] == "fisher_yates":
        return fisher_yates_samlper(spec["n_tot"], spec["M"], spec["B"])
    return hybrid_fisher_iwor_sampler(spec["N"], spec["m"], spec["M"], spec["B"])


def pin_against_r(run_dir: Path, draws: dict[str, np.ndarray]) -> dict:
    """R's own draws for this object, against the replica, over every draw."""
    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / "pin.R"
        script.write_text(_PIN_R)
        done = subprocess.run(
            [
                "Rscript",
                str(script),
                str(run_dir / "sceptre_object.rds"),
                ",".join(map(str, PINNED_DRAWS)),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    theirs = json.loads(done.stdout)
    out = {}
    for name, d in draws.items():
        r = theirs[name]
        weights = np.arange(1, d.shape[1] + 1, dtype=np.int64)
        rows = [i for i in PINNED_DRAWS if i < d.shape[0]]
        out[name] = {
            "shape_equal": [r["B"], r["width"]] == list(d.shape),
            "sum_entries_equal": int(r["sum_entries"]) == int(d.sum()),
            "sum_position_weighted_equal": int(r["sum_position_weighted"])
            == int((d * weights).sum()),
            "pinned_rows_equal": all(
                np.array_equal(d[i], np.asarray(row, dtype=np.int64))
                for i, row in zip(rows, r["pinned_rows"], strict=True)
            ),
        }
        out[name]["all_equal"] = all(out[name].values())
    return out


def run_r_exact(
    analysis: str, e, r: pd.DataFrame, settings: dict, pool, draws, n_jobs: int
) -> pd.DataFrame:
    """One analysis on R's own permutation draws, through the low-level entry points."""
    common = dict(
        B1=settings["B1"],
        B2=settings["B2"],
        B3=settings["B3"],
        fit_parametric_curve=settings["resampling_approximation"] == "skew_normal",
        side_code=SIDE_CODES[settings["side"]],
        seed=SEED,
        n_jobs=n_jobs,
        resampling_mechanism="permutations",
        permutations=draws,
    )
    pairs = r.loc[r["pass_qc"].astype(bool), KEY].reset_index(drop=True)
    if analysis in ("discovery", "power"):
        if pool is None:
            return run_discovery_ntcells_complement(
                e.response_matrix,
                e.gene_ids,
                e.covariate_matrix,
                e.grna_target_cells,
                pairs,
                **common,
            )
        return run_discovery_nt_cells(
            e.response_matrix,
            e.gene_ids,
            e.covariate_matrix,
            e.grna_target_cells,
            pool,
            pairs,
            **common,
        )
    universe = calibration_universe(e, pool)
    groups = calibration_groups(e, pairs, universe)
    response = e.response_matrix if pool is None else e.response_matrix[:, universe]
    return run_discovery_ntcells_complement(
        response, e.gene_ids, e.covariate_matrix[universe], groups, pairs, **common
    )


# --- metrics -------------------------------------------------------------------------------


def merge(py: pd.DataFrame, r: pd.DataFrame) -> pd.DataFrame:
    return r.merge(py, on=KEY, how="inner", suffixes=("_r", "_py"), validate="one_to_one")


def bh_calls(p, alpha: float) -> np.ndarray:
    """BH at `alpha`, as R's `p.adjust(method = "BH") < alpha`."""
    return stats.false_discovery_control(np.clip(np.asarray(p, dtype=float), 0, 1)) < alpha


def two_by_two(py: np.ndarray, r: np.ndarray) -> dict:
    py, r = np.asarray(py, dtype=bool), np.asarray(r, dtype=bool)
    return {
        "both": int((py & r).sum()),
        "pysceptre_only": int((py & ~r).sum()),
        "r_only": int((~py & r).sum()),
        "neither": int((~py & ~r).sum()),
    }


def _pearson(x, y) -> float:
    x, y = np.asarray(x, dtype=float), np.asarray(y, dtype=float)
    if x.size < 2 or np.ptp(x) == 0 or np.ptp(y) == 0:
        return float("nan")
    return float(stats.pearsonr(x, y).statistic)


def deterministic_metrics(m: pd.DataFrame, max_listed: int = 10) -> dict:
    """Fold change and `z_orig`: nothing resampled enters either.

    Pairs whose `z_orig` differs by more than 1e-6 relative are listed, since
    the maximum alone does not say whether one pair or many moved.
    """
    log2_py = np.log2(m["fold_change_py"].to_numpy(float))
    log2_r = m["log_2_fold_change"].to_numpy(float)
    z_py, z_r = m["z_orig_py"].to_numpy(float), m["z_orig_r"].to_numpy(float)
    dz = np.abs(z_py - z_r)
    rel = dz / np.maximum(np.abs(z_r), 1e-300)
    off = np.flatnonzero(rel > 1e-6)
    off = off[np.argsort(-rel[off])][:max_listed]
    return {
        "log2_fold_change_pearson_r": _pearson(log2_py, log2_r),
        "log2_fold_change_max_abs_diff": float(np.max(np.abs(log2_py - log2_r))),
        "log2_fold_change_abs_diff_gt_1e-9": int((np.abs(log2_py - log2_r) > 1e-9).sum()),
        "z_orig_max_abs_diff": float(dz.max()),
        "z_orig_max_rel_diff": float(rel.max()),
        "z_orig_rel_diff_gt_1e-6": int((rel > 1e-6).sum()),
        "z_orig_rel_diff_gt_1e-6_pairs": [
            {
                "response_id": m["response_id"].iloc[i],
                "grna_target": m["grna_target"].iloc[i],
                "z_r": float(z_r[i]),
                "z_py": float(z_py[i]),
                "rel_diff": float(rel[i]),
                "n_nonzero_trt": int(m["n_nonzero_trt"].iloc[i])
                if "n_nonzero_trt" in m
                else int(m["n_nonzero_trt_r"].iloc[i]),
            }
            for i in off
        ],
    }


# Relative agreement asked of a stage-2 p-value, against R or against the reference below.
SN_RTOL = 1e-6


def _log_left_tail(x: float, alpha: float) -> float:
    """log of the standard skew-normal CDF at `x`, without cancellation.

    `2 * integral of phi(t) Phi(alpha t)` up to `x`, with `phi(x)` and
    `Phi(alpha x)` factored out of the integrand. Evaluating the CDF as
    `Phi(x) - 2 T(x, alpha)` instead loses all relative precision once the
    result is many orders below `Phi(x)`, on the light side of the skew.
    """
    base = special.log_ndtr(alpha * x)

    def scaled(s):
        return np.exp(x * s - 0.5 * s * s + special.log_ndtr(alpha * (x - s)) - base)

    val, _ = integrate.quad(scaled, 0, np.inf, epsabs=0, epsrel=1e-13, limit=500)
    return math.log(2.0) - 0.5 * x * x - 0.5 * math.log(2 * math.pi) + base + math.log(val)


def skew_normal_reference_p(z: float, xi: float, omega: float, alpha: float, side_code: int):
    """The stage-2 p-value at the given fit, evaluated as `_log_left_tail` does.

    The tail follows the fit's median, standing in for the null median R
    compares `z` with; at stage 2 `z` lies far enough out that both agree.
    Floored at 1e-250 like both implementations.
    """
    x = (z - xi) / omega
    right = z >= skewnorm.median(alpha, loc=xi, scale=omega)
    if side_code == 1 or (side_code == 0 and right):
        log_p = _log_left_tail(-x, -alpha)
    else:
        log_p = _log_left_tail(x, alpha)
    return max(math.exp(log_p) * (2.0 if side_code == 0 else 1.0), 1e-250)


def stage_2_against_reference(m: pd.DataFrame, side_code: int) -> dict:
    """Stage-2 p-values on R's draws, against R and against an independent evaluation.

    Both sides fit the same skew normal to the same null statistics, so a
    disagreement can only come from evaluating its tail. Each pair is checked
    against R and against `skew_normal_reference_p` at R's own `xi`, `omega`,
    `alpha` and `z_orig`; a pair is explained when R is off the reference and
    pysceptre is on it.
    """
    s2 = m[m["stage_r"].to_numpy() == 2]
    if s2.empty:
        return {"stage_2": 0}
    ref = np.array(
        [
            skew_normal_reference_p(z, xi, om, al, side_code)
            for z, xi, om, al in zip(
                s2["z_orig_r"], s2["xi"], s2["omega"], s2["alpha"], strict=True
            )
        ]
    )
    p_py, p_r = s2["p_value_py"].to_numpy(float), s2["p_value_r"].to_numpy(float)
    vs_r = np.abs(p_py / p_r - 1)
    r_err = np.abs(p_r / ref - 1)
    py_err = np.abs(p_py / ref - 1)
    agree = vs_r <= SN_RTOL
    r_off = r_err > SN_RTOL
    explained = ~agree & r_off & (py_err <= SN_RTOL)
    r_ok = ~r_off
    return {
        "stage_2": int(len(s2)),
        "within_rtol_of_r": int(agree.sum()),
        "r_off_reference": int(r_off.sum()),
        "explained_by_r_tail_error": int(explained.sum()),
        "unexplained": int((~agree & ~explained).sum()),
        "max_rel_diff_where_r_on_reference": float(vs_r[r_ok].max()) if r_ok.any() else None,
        "max_rel_err_vs_reference_py": float(py_err.max()),
        "max_rel_err_vs_reference_r": float(r_err.max()),
        "r_p_range_where_r_off_reference": [float(p_r[r_off].min()), float(p_r[r_off].max())]
        if r_off.any()
        else None,
        "rtol": SN_RTOL,
    }


def p_agreement(m: pd.DataFrame) -> dict:
    p_py, p_r = m["p_value_py"].to_numpy(float), m["p_value_r"].to_numpy(float)
    return {
        "spearman_rho": float(stats.spearmanr(p_py, p_r).statistic) if len(m) > 1 else float("nan"),
        "pearson_r_neg_log10_p": _pearson(-np.log10(p_py), -np.log10(p_r)),
        "stage_agree": int((m["stage_py"].to_numpy() == m["stage_r"].to_numpy()).sum()),
        "stage_counts_py": stage_counts(m["stage_py"]),
        "stage_counts_r": stage_counts(m["stage_r"]),
    }


def stage_counts(stage: pd.Series) -> dict:
    return {str(int(k)): int(v) for k, v in stage.value_counts().sort_index().items()}


def calls_metrics(analysis: str, m: pd.DataFrame, alpha: float) -> dict:
    """BH calls against R's, and the calibration and power summaries."""
    out: dict = {}
    p_py, p_r = m["p_value_py"].to_numpy(float), m["p_value_r"].to_numpy(float)
    if "significant" in m:
        r_sig = m["significant"].to_numpy(bool)
        out["bh_on_r_p_reproduces_r_significant"] = bool(
            np.array_equal(bh_calls(p_r, alpha), r_sig)
        )
        py_sig = bh_calls(p_py, alpha)
        out["bh_2x2"] = two_by_two(py_sig, r_sig)
    if analysis == "calibration":
        out["ks_vs_uniform_py"] = float(stats.kstest(np.clip(p_py, 0, 1), "uniform").statistic)
        out["ks_vs_uniform_r"] = float(stats.kstest(np.clip(p_r, 0, 1), "uniform").statistic)
        out["false_discoveries_py"] = int(bh_calls(p_py, alpha).sum())
        out["false_discoveries_r"] = int(m["significant"].to_numpy(bool).sum())
    if analysis == "power":
        out["median_log2_fold_change_py"] = float(np.median(np.log2(m["fold_change_py"])))
        out["median_log2_fold_change_r"] = float(np.median(m["log_2_fold_change"]))
        out["median_p_py"] = float(np.median(p_py))
        out["median_p_r"] = float(np.median(p_r))
    return out


def exact_p_metrics(m: pd.DataFrame, alpha: float, side_code: int, max_listed: int = 25) -> dict:
    """Value-for-value agreement when both sides used the same draws."""
    p_py, p_r = m["p_value_py"].to_numpy(float), m["p_value_r"].to_numpy(float)
    diff = np.abs(p_py - p_r)
    rel = diff / np.maximum(np.abs(p_r), 1e-300)
    equal = p_py == p_r
    stage_r = m["stage_r"].to_numpy()
    stage_py = m["stage_py"].to_numpy()
    out = {
        "n": int(len(m)),
        "p_exactly_equal": int(equal.sum()),
        "p_max_abs_diff": float(diff.max()) if len(m) else float("nan"),
        "p_max_rel_diff": float(rel.max()) if len(m) else float("nan"),
        "stage_agree": int((stage_py == stage_r).sum()),
        "unequal_by_r_stage": {
            str(int(k)): int(v) for k, v in Counter(stage_r[~equal].tolist()).items()
        },
        "stage_1_or_3_unequal": int((~equal & (stage_r != 2)).sum()),
        "stage_counts_r": stage_counts(m["stage_r"]),
    }
    for stage in (1, 2, 3):
        sel = stage_r == stage
        if sel.any():
            out[f"stage_{stage}_max_rel_diff"] = float(rel[sel].max())
    out["stage_2_check"] = stage_2_against_reference(m, side_code)
    if "significant" in m:
        out["bh_2x2"] = two_by_two(bh_calls(p_py, alpha), m["significant"].to_numpy(bool))
    order = np.argsort(-rel)
    listed = [i for i in order if not equal[i]][:max_listed]
    cols = [c for c in ("xi", "omega", "alpha") if c in m]
    out["largest_differences"] = [
        {
            "response_id": m["response_id"].iloc[i],
            "grna_target": m["grna_target"].iloc[i],
            "stage_r": int(stage_r[i]),
            "stage_py": int(stage_py[i]),
            "p_r": float(p_r[i]),
            "p_py": float(p_py[i]),
            "rel_diff": float(rel[i]),
            **{f"r_{c}": float(m[c].iloc[i]) for c in cols},
        }
        for i in listed
    ]
    return out


def qc_agreement(trt, cntrl, passed, r_trt, r_cntrl, r_passed) -> dict:
    """Exact agreement of nonzero counts and `pass_qc` with R's, row for row."""
    r_passed = np.asarray(r_passed, dtype=bool)
    return {
        "pairs": int(r_passed.size),
        "n_nonzero_trt_equal": int((np.asarray(trt) == np.asarray(r_trt)).sum()),
        "n_nonzero_cntrl_equal": int((np.asarray(cntrl) == np.asarray(r_cntrl)).sum()),
        "pass_qc_equal": int((np.asarray(passed, dtype=bool) == r_passed).sum()),
        "pass_qc_r": int(r_passed.sum()),
    }


def _qc_against(r: pd.DataFrame, trt, cntrl, passed) -> dict:
    return qc_agreement(trt, cntrl, passed, r["n_nonzero_trt"], r["n_nonzero_cntrl"], r["pass_qc"])


def discovery_pairwise_qc(e, r: pd.DataFrame, pool, settings: dict) -> dict:
    """Nonzero counts for every discovery pair R listed, passing QC or not.

    A target QC left without cells is absent from the export; its pairs count
    zero treated cells, as in R.
    """
    targets = list(dict.fromkeys(r["grna_target"]))
    empty = np.empty(0, dtype=np.int64)
    cells = [np.asarray(e.grna_target_cells.get(t, empty), dtype=np.int64) for t in targets]
    trt, cntrl = nonzero_counts(
        e.response_matrix, cells, e.covariate_matrix.shape[0], control_cells=pool
    )
    rows = r["response_id"].map({g: i for i, g in enumerate(e.gene_ids)}).to_numpy()
    cols = r["grna_target"].map({t: j for j, t in enumerate(targets)}).to_numpy()
    t, c = trt[rows, cols], cntrl[rows, cols]
    passed = (t >= settings["n_nonzero_trt_thresh"]) & (c >= settings["n_nonzero_cntrl_thresh"])
    out = _qc_against(r, t, c, passed)
    out["targets_without_cells"] = [t for t in targets if t not in e.grna_target_cells]
    return out


def calibration_pairwise_qc(e, r: pd.DataFrame, pool, settings: dict) -> dict:
    """Nonzero counts for R's negative control pairs, within the calibration universe."""
    universe = calibration_universe(e, pool)
    groups = calibration_groups(e, r[KEY], universe)
    names = list(groups)
    response = e.response_matrix if pool is None else e.response_matrix[:, universe]
    trt, cntrl = nonzero_counts(response, [groups[n] for n in names], universe.size)
    rows = r["response_id"].map({g: i for i, g in enumerate(e.gene_ids)}).to_numpy()
    cols = r["grna_target"].map({n: j for j, n in enumerate(names)}).to_numpy()
    t, c = trt[rows, cols], cntrl[rows, cols]
    passed = (t >= settings["n_nonzero_trt_thresh"]) & (c >= settings["n_nonzero_cntrl_thresh"])
    out = _qc_against(r, t, c, passed)
    out["groups"] = len(names)
    return out


# --- one run -------------------------------------------------------------------------------


def compare_run(run_dir: Path, n_jobs_list: list[int], pin: bool) -> dict:
    info = json.loads((run_dir / "run_info.json").read_text())
    e = load_export(run_dir / "export")
    settings = check_settings(e, info)
    alpha = settings["multiple_testing_alpha"]
    n_cells = settings["n_cells"]
    pool = (
        nt_cell_pool(e.ntc_grna_cells, n_cells) if settings["control_group"] == "nt_cells" else None
    )
    out: dict = {
        "settings": settings,
        "r_versions": info["versions"],
        "r_status": info["status"],
        "seed": SEED,
    }
    if pool is not None:
        same = bool(np.array_equal(pool, e.all_nt_idxs))
        out["nt_pool_equals_all_nt_idxs"] = same
        print(f"   NT pool from ntc_grna_cells == R's all_nt_idxs: {same} ({pool.size} cells)")
        if not same:
            raise SystemExit(
                "the NT pool is not R's all_nt_idxs; R's draws would index other cells"
            )

    r = {a: read_r(run_dir, a) for a in ANALYSES}
    out["pairwise_qc"] = {
        "discovery": discovery_pairwise_qc(e, r["discovery"], pool, settings),
        "calibration": calibration_pairwise_qc(e, r["calibration"], pool, settings),
    }

    # One untimed call first, so numba's compile cost is not charged to a timed analysis.
    timed(lambda: run_own("power", e, r["power"], settings, 1))

    analyses: dict = {}
    for a in ANALYSES:
        res: dict = {"wall_time_s": {}}
        frames = {}
        for n in n_jobs_list:
            frame, secs, caught = timed(lambda a=a, n=n: run_own(a, e, r[a], settings, n))
            frames[n] = frame
            res["wall_time_s"][f"pysceptre_n_jobs_{n}"] = secs
            if n == n_jobs_list[0]:
                res["warnings"] = caught
            print(f"   {a:<11} own RNG, n_jobs={n}: {secs:7.1f} s, {len(frame)} rows")
        res["wall_time_s"]["r"] = info["wall_time_s"][R_STEP[a]]
        first = frames[n_jobs_list[0]]
        res["n_jobs_results_identical"] = all(f.equals(first) for f in frames.values())
        tested = r_tested(r[a])
        m = merge(first, tested)
        res["r_rows"] = int(len(r[a]))
        res["r_tested"] = int(len(tested))
        res["merged"] = int(len(m))
        res["deterministic"] = deterministic_metrics(m)
        res["own_rng"] = {**p_agreement(m), **calls_metrics(a, m, alpha)}
        if a == "power":
            # Every positive control, including any that failed QC, which the power check
            # reports rather than drops.
            full = merge(first, r[a])
            res["pairwise_qc"] = qc_agreement(
                full["n_nonzero_trt_py"],
                full["n_nonzero_cntrl_py"],
                full["pass_qc_py"],
                full["n_nonzero_trt_r"],
                full["n_nonzero_cntrl_r"],
                full["pass_qc_r"],
            )
            res["pairwise_qc"]["pairs"] = int(len(r[a]))
            res["pairwise_qc"]["merged"] = int(len(full))
        analyses[a] = res

    if settings["resampling_mechanism"] == "permutations":
        specs = sampler_specs(e, settings, pool)
        out["r_sampler_specs"] = specs
        problems = check_specs_against_r(specs, info, pool)
        out["r_sampler_specs_match_run_info"] = not problems
        if problems:
            raise SystemExit("sampler sizing disagrees with run_info.json: " + "; ".join(problems))
        n_exact = max(n_jobs_list)
        draws = {"discovery": make_draws(specs["discovery"])}
        if pin:
            draws["calibration"] = make_draws(specs["calibration"])
            out["r_sampler_pin"] = pin_against_r(run_dir, draws)
            print(f"   replica pinned against R's own draws: {out['r_sampler_pin']}")
            if not all(v["all_equal"] for v in out["r_sampler_pin"].values()):
                raise SystemExit("the replica does not reproduce R's draws for this object")
        for a in ("discovery", "power", "calibration"):
            source = "calibration" if a == "calibration" else "discovery"
            if source not in draws:
                draws = {source: make_draws(specs[source])}
            frame, secs, caught = timed(
                lambda a=a, d=draws[source]: run_r_exact(a, e, r[a], settings, pool, d, n_exact)
            )
            m = merge(frame, r_tested(r[a]))
            analyses[a]["r_exact"] = {
                "n_jobs": n_exact,
                "wall_time_s": secs,
                "merged": int(len(m)),
                "warnings": caught,
                "deterministic": deterministic_metrics(m),
                **exact_p_metrics(m, alpha, SIDE_CODES[settings["side"]]),
            }
            ex = analyses[a]["r_exact"]
            print(
                f"   {a:<11} R's draws: {secs:7.1f} s, {ex['p_exactly_equal']}/{ex['n']} p-values "
                f"exactly equal, max rel diff {ex['p_max_rel_diff']:.3g}"
            )
        del draws
    out["analyses"] = analyses
    return out


# --- output --------------------------------------------------------------------------------


def source_digest() -> dict:
    """A SHA-256 over the code a comparison runs: the package, the loader and the replica.

    `git describe --dirty` cannot tell two uncommitted states apart; this can.
    Taken when the run starts, which is when the modules are imported.
    """
    package = Path(pysceptre.__file__).resolve().parent
    files = sorted(package.rglob("*.py")) + [
        REPO / "scripts" / "sceptre_io.py",
        REPO / "scripts" / "compare_sceptredata.py",
        REPO / "tests" / "validation" / "r_samplers.py",
    ]
    digest = hashlib.sha256()
    for f in files:
        digest.update(str(f.relative_to(REPO)).encode())
        digest.update(f.read_bytes())
    return {
        "sha256": digest.hexdigest(),
        "covers": "src/pysceptre/**/*.py, scripts/sceptre_io.py, "
        "scripts/compare_sceptredata.py, tests/validation/r_samplers.py",
        "n_files": len(files),
    }


def environment() -> dict:
    def git(*args):
        try:
            return subprocess.run(
                ["git", "-C", str(REPO), *args], capture_output=True, text=True, check=True
            ).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            return None

    try:
        import numba

        numba_version = numba.__version__
    except ImportError:
        numba_version = None
    return {
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        # The imported package and the commit it sits on; an editable install's
        # distribution metadata keeps the version it was installed at.
        "pysceptre_path": str(Path(pysceptre.__file__).resolve().parent),
        "pysceptre_dist_metadata": metadata.version("pysceptre"),
        "git": git("describe", "--always", "--dirty"),
        "source": source_digest(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "machine": platform.machine(),
        "cpu_count": os.cpu_count(),
        "numpy": np.__version__,
        "scipy": metadata.version("scipy"),
        "pandas": pd.__version__,
        "numba": numba_version,
        "parallel_note": (
            "n_jobs > 1 uses threads off Linux; timings are wall clock on this machine, "
            "R's are from run_info.json (parallel = FALSE)"
        ),
    }


def refuse_unless_ignored(path: Path) -> None:
    """Refuse a path inside a git work tree that git does not ignore."""
    anchor = path.parent
    while not anchor.exists():
        anchor = anchor.parent
    inside = subprocess.run(
        ["git", "-C", str(anchor), "rev-parse", "--is-inside-work-tree"],
        capture_output=True,
        text=True,
    )
    if inside.returncode != 0 or inside.stdout.strip() != "true":
        return
    ignored = subprocess.run(["git", "-C", str(anchor), "check-ignore", "-q", str(path.resolve())])
    if ignored.returncode != 0:
        raise SystemExit(
            f"refusing to write {path}: it is inside a git work tree and not ignored, and the "
            "comparison is derived from real screen data"
        )


def _plain(x):
    """JSON-ready: plain Python types, and NaN or infinity as null."""
    if isinstance(x, dict):
        return {str(k): _plain(v) for k, v in x.items()}
    if isinstance(x, (list, tuple, np.ndarray)):
        return [_plain(v) for v in x]
    if isinstance(x, np.generic):
        x = x.item()
    if isinstance(x, float) and not np.isfinite(x):
        return None
    return x


def write_json(results: dict, path: Path) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(_plain(results), indent=2) + "\n")
    tmp.replace(path)


def _g(x, digits: int = 3) -> str:
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    if isinstance(x, (int, np.integer)):
        return str(x)
    if x == 0:
        return "0"
    return f"{x:.{digits}g}"


def _calls(t: dict | None) -> str:
    if not t:
        return ""
    return f"{t['both']}/{t['pysceptre_only']}/{t['r_only']}/{t['neither']}"


def _qc_cell(q: dict | None) -> str:
    if not q:
        return ""
    n = q["pairs"]
    vals = (q["n_nonzero_trt_equal"], q["n_nonzero_cntrl_equal"], q["pass_qc_equal"])
    if all(v == n for v in vals):
        return f"{n}/{n} exact"
    return f"trt {vals[0]}/{n}, cntrl {vals[1]}/{n}, pass_qc {vals[2]}/{n}"


def _stage_2_cell(ex: dict | None) -> str:
    if not ex:
        return ""
    c = ex["stage_2_check"]
    if not c["stage_2"]:
        return "no stage 2"
    return (
        f"{c['within_rtol_of_r']}/{c['stage_2']} / {c['explained_by_r_tail_error']} / "
        f"{c['unexplained']}"
    )


def _py_wall(wall: dict) -> dict[int, float]:
    """pysceptre's wall times keyed by n_jobs, in n_jobs order."""
    prefix = "pysceptre_n_jobs_"
    found = {int(k[len(prefix) :]): v for k, v in wall.items() if k.startswith(prefix)}
    return dict(sorted(found.items()))


def markdown_table(results: dict) -> str:
    n_jobs_seen = sorted(
        {
            n
            for run in results.get("runs", {}).values()
            for res in run["analyses"].values()
            for n in _py_wall(res["wall_time_s"])
        }
    )
    head = [
        "run",
        "analysis",
        "pairs merged",
        "n_nonzero + pass_qc",
        "log2 FC r; max abs diff",
        "z max abs; max rel diff",
        "own RNG p: Spearman; Pearson -log10 p",
        "own RNG BH 2x2 both/py only/R only/neither",
        "R draws p: equal/n; max abs; max rel diff",
        "R draws stage 2: within 1e-6 of R / R tail error / unexplained",
        "R draws BH 2x2",
        "calibration KS py/R; false discoveries py/R",
        "power median log2 FC py/R",
        "wall s " + " / ".join(f"py n_jobs={n}" for n in n_jobs_seen) + " / R",
    ]
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    for key, run in sorted(results.get("runs", {}).items()):
        qc = run.get("pairwise_qc", {})
        for a in ANALYSES:
            res = run["analyses"][a]
            det, own = res["deterministic"], res["own_rng"]
            ex = res.get("r_exact")
            q = res.get("pairwise_qc") if a == "power" else qc.get(a)
            wall = res["wall_time_s"]
            py_wall = _py_wall(wall)
            py_times = " / ".join(_g(py_wall.get(n), 3) for n in n_jobs_seen)
            row = [
                key,
                a,
                f"{res['merged']}/{res['r_tested']}",
                _qc_cell(q),
                f"{_g(det['log2_fold_change_pearson_r'], 10)}; "
                f"{_g(det['log2_fold_change_max_abs_diff'])}",
                f"{_g(det['z_orig_max_abs_diff'])}; {_g(det['z_orig_max_rel_diff'])}"
                + (
                    f" ({det['z_orig_rel_diff_gt_1e-6']} pair > 1e-6)"
                    if det["z_orig_rel_diff_gt_1e-6"]
                    else ""
                ),
                f"{_g(own['spearman_rho'], 4)}; {_g(own['pearson_r_neg_log10_p'], 4)}",
                _calls(own.get("bh_2x2")),
                (
                    f"{ex['p_exactly_equal']}/{ex['n']}; {_g(ex['p_max_abs_diff'])}; "
                    f"{_g(ex['p_max_rel_diff'])}"
                )
                if ex
                else "",
                _stage_2_cell(ex),
                _calls(ex.get("bh_2x2")) if ex else "",
                (
                    f"{_g(own['ks_vs_uniform_py'])}/{_g(own['ks_vs_uniform_r'])}; "
                    f"{own['false_discoveries_py']}/{own['false_discoveries_r']}"
                )
                if a == "calibration"
                else "",
                (
                    f"{_g(own['median_log2_fold_change_py'], 4)}/"
                    f"{_g(own['median_log2_fold_change_r'], 4)}"
                )
                if a == "power"
                else "",
                f"{py_times} / {_g(wall['r'], 3)}",
            ]
            lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def print_run(key: str, run: dict) -> None:
    s = run["settings"]
    print(
        f"\n== {key}: {s['moi']} MOI, {s['control_group']}, {s['resampling_mechanism']}, "
        f"side={s['side']}, {s['n_genes']} genes x {s['n_cells']} cells"
    )
    qcs = {**run["pairwise_qc"], "power": run["analyses"]["power"].get("pairwise_qc")}
    for name, q in qcs.items():
        if q:
            print(f"   pairwise QC, {name}: {_qc_cell(q)} (R pass_qc {q['pass_qc_r']})")
    for a in ANALYSES:
        res = run["analyses"][a]
        own = res["own_rng"]
        print(
            f"   {a:<11} merged {res['merged']}/{res['r_tested']}, n_jobs identical "
            f"{res['n_jobs_results_identical']}, stages py {own['stage_counts_py']} "
            f"R {own['stage_counts_r']}"
        )
        if "bh_on_r_p_reproduces_r_significant" in own:
            print(
                f"      BH on R's p reproduces R's calls: {own['bh_on_r_p_reproduces_r_significant']}"
            )
        ex = res.get("r_exact")
        if ex:
            print(
                f"      R's draws: {ex['p_exactly_equal']}/{ex['n']} equal, stage agree "
                f"{ex['stage_agree']}, unequal by R stage {ex['unequal_by_r_stage']}, "
                f"max rel diff by stage "
                + ", ".join(
                    f"{k[6]}: {_g(ex[k])}"
                    for k in ex
                    if k.startswith("stage_") and k.endswith("rel_diff")
                )
            )
            c = ex["stage_2_check"]
            if c["stage_2"]:
                print(
                    f"      R's draws, stage 2: {c['within_rtol_of_r']}/{c['stage_2']} within "
                    f"{c['rtol']:g} of R; R off the reference on {c['r_off_reference']} "
                    f"(R p in {c['r_p_range_where_r_off_reference']}), explained "
                    f"{c['explained_by_r_tail_error']}, unexplained {c['unexplained']}; "
                    f"pysceptre max rel error vs reference {_g(c['max_rel_err_vs_reference_py'])}"
                )
        for det_name, det in (("own RNG", res["deterministic"]),) + (
            (("R's draws", ex["deterministic"]),) if ex else ()
        ):
            for row in det["z_orig_rel_diff_gt_1e-6_pairs"]:
                print(
                    f"      z_orig off by {row['rel_diff']:.3g} ({det_name}): "
                    f"{row['response_id']} / {row['grna_target']}, R {row['z_r']:.10g}, "
                    f"pysceptre {row['z_py']:.10g}"
                )
        for w in res.get("warnings", []):
            print(f"      warning x{w['count']}: {w['message'][:160]}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("dirs", nargs="+", type=Path)
    parser.add_argument("--json", type=Path, default=None)
    parser.add_argument("--n-jobs", type=int, nargs="+", default=[1, 8])
    parser.add_argument("--pin-samplers", action="store_true")
    args = parser.parse_args()

    runs = find_runs(args.dirs)
    out_path = args.json or (runs[0].parent.parent / "comparison.json")
    refuse_unless_ignored(out_path)
    results = json.loads(out_path.read_text()) if out_path.exists() else {}
    results.setdefault("runs", {})
    results["environment"] = environment()

    for run_dir in runs:
        key = run_key(run_dir)
        print(f"\n== {key}")
        start = time.perf_counter()
        results["runs"][key] = compare_run(run_dir, args.n_jobs, args.pin_samplers)
        results["runs"][key]["comparison_wall_time_s"] = time.perf_counter() - start
        write_json(results, out_path)

    for key, run in sorted(results["runs"].items()):
        print_run(key, run)
    table = markdown_table(results)
    results["markdown_table"] = table
    write_json(results, out_path)
    print("\n" + table)
    print(f"\nwrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
